services:
  db:
    image: postgres:14
    container_name: ls_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 10

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    restart: unless-stopped
    env_file: .env
    environment:
      DJANGO_DB: default
      POSTGRE_NAME: ${POSTGRES_DB}
      POSTGRE_USER: ${POSTGRES_USER}
      POSTGRE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRE_HOST: db
      POSTGRE_PORT: ${POSTGRES_PORT}
      LABEL_STUDIO_USERNAME: ${LS_USERNAME}
      LABEL_STUDIO_PASSWORD: ${LS_PASSWORD}
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    ports:
      - 8080:8080
    volumes:
      - ./data/labelstudio_data:/label-studio/data
      - ./data/projects:/label-studio/projects
    depends_on:
      - db

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81 # admin panel
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  backup:
    image: offen/docker-volume-backup:latest
    container_name: ls_backup
    restart: unless-stopped
    env_file: .env
    environment:
      BACKUP_CRON_EXPRESSION: "${CRON_SCHEDULE:-0 2 * * *}"
      BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_PRUNING_PREFIX: "backup-"
      BACKUP_RETENTION_DAYS: "14"
      TZ: "UTC"
    volumes:
      - ./data/pgdata:/backup/pgdata:ro
      - ./data/labelstudio_data:/backup/labelstudio_data:ro
      - ./data/projects:/backup/projects:ro
      - ./backups:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - db
      - labelstudio
networks:
  default:
    name: ls_network
